name: build_docker

on:
  create:
    tags:
      - '*.*.*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout commit"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: dankersw
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "build docker images"
        run: |
          DOCKER_REPO="zephyr_builder"
          DOCKER_ACC="dankersw"
          PLATFORM="linux/amd64,linux/arm64"

          GITHUB_TAG=${GITHUB_REF#refs/tags/*/}
          readarray -d / -t TAG_PATH <<< "$GITHUB_TAG"
          GIT_TAG="${TAG_PATH[2]}"

          echo "Building AMD64 and ARM64 for tag $GIT_TAG"
          docker buildx build -t $DOCKER_ACC/$DOCKER_REPO:$GIT_TAG -f docker/zephyr_builder.dockerfile . --build-arg tag=$GIT_TAG --platform $PLATFORM --push